#include <host/ble_gap.h>

#define EventName(eve) [eve] = #eve,

const char *events[] = {
    EventName(BLE_GAP_EVENT_CONNECT)
    EventName(BLE_GAP_EVENT_DISCONNECT)
    /* Reserved                                 2 */
    EventName(BLE_GAP_EVENT_CONN_UPDATE)
    EventName(BLE_GAP_EVENT_CONN_UPDATE_REQ)
    EventName(BLE_GAP_EVENT_L2CAP_UPDATE_REQ)
    EventName(BLE_GAP_EVENT_TERM_FAILURE)
    EventName(BLE_GAP_EVENT_DISC)
    EventName(BLE_GAP_EVENT_DISC_COMPLETE)
    EventName(BLE_GAP_EVENT_ADV_COMPLETE)
    EventName(BLE_GAP_EVENT_ENC_CHANGE)
    EventName(BLE_GAP_EVENT_PASSKEY_ACTION)
    EventName(BLE_GAP_EVENT_NOTIFY_RX)
    EventName(BLE_GAP_EVENT_NOTIFY_TX)
    EventName(BLE_GAP_EVENT_SUBSCRIBE)
    EventName(BLE_GAP_EVENT_MTU)
    EventName(BLE_GAP_EVENT_IDENTITY_RESOLVED)
    EventName(BLE_GAP_EVENT_REPEAT_PAIRING)
    EventName(BLE_GAP_EVENT_PHY_UPDATE_COMPLETE)
    EventName(BLE_GAP_EVENT_EXT_DISC)
    EventName(BLE_GAP_EVENT_PERIODIC_SYNC)
    EventName(BLE_GAP_EVENT_PERIODIC_REPORT)
    EventName(BLE_GAP_EVENT_PERIODIC_SYNC_LOST)
    EventName(BLE_GAP_EVENT_SCAN_REQ_RCVD)
    EventName(BLE_GAP_EVENT_PERIODIC_TRANSFER)
    EventName(BLE_GAP_EVENT_PATHLOSS_THRESHOLD)
    EventName(BLE_GAP_EVENT_TRANSMIT_POWER)
    EventName(BLE_GAP_EVENT_PARING_COMPLETE)
    EventName(BLE_GAP_EVENT_SUBRATE_CHANGE)
    EventName(BLE_GAP_EVENT_VS_HCI)
    EventName(BLE_GAP_EVENT_BIGINFO_REPORT)
    EventName(BLE_GAP_EVENT_REATTEMPT_COUNT)
    EventName(BLE_GAP_EVENT_AUTHORIZE)
    EventName(BLE_GAP_EVENT_TEST_UPDATE)
    EventName(BLE_GAP_EVENT_DATA_LEN_CHG)
    EventName(BLE_GAP_EVENT_CONNLESS_IQ_REPORT)
    EventName(BLE_GAP_EVENT_CONN_IQ_REPORT)
    EventName(BLE_GAP_EVENT_CTE_REQ_FAILED)

    //TODO : Deprecate the EVENT_LINK_ESTAB going ahead
    EventName(BLE_GAP_EVENT_LINK_ESTAB)
    EventName(BLE_GAP_EVENT_EATT)
    EventName(BLE_GAP_EVENT_PER_SUBEV_DATA_REQ)
    EventName(BLE_GAP_EVENT_PER_SUBEV_RESP)
    EventName(BLE_GAP_EVENT_PERIODIC_TRANSFER_V2)

    /* ISO events */
    EventName(BLE_GAP_EVENT_CIS_ESTAB)
    EventName(BLE_GAP_EVENT_CIS_REQUEST)
    EventName(BLE_GAP_EVENT_CREATE_BIG_COMP)
    EventName(BLE_GAP_EVENT_TERM_BIG_COMP)
    EventName(BLE_GAP_EVENT_BIG_SYNC_ESTAB)
    EventName(BLE_GAP_EVENT_BIG_SYNC_LOST)
    EventName(BLE_GAP_EVENT_BIGINFO_ADV_RPT)
    EventName(BLE_GAP_EVENT_CIS_ESTAB_V2)

    EventName(BLE_GAP_EVENT_RD_ALL_REM_FEAT)
    EventName(BLE_GAP_EVENT_MONITOR_ADV_REPORT)

    EventName(BLE_GAP_EVENT_CACHE_ASSOC)
};
