CMAKE_MINIMUM_REQUIRED(VERSION 4.1)
ADD_COMPILE_DEFINITIONS(TESTER)
ADD_EXECUTABLE(${CMAKE_PROJECT_NAME}
        main.cpp
        config_payload.cpp
)
TARGET_INCLUDE_DIRECTORIES(${CMAKE_PROJECT_NAME}
        PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/../../../components/protocol/include
)
TARGET_LINK_LIBRARIES(${CMAKE_PROJECT_NAME}
        PRIVATE CLI11::CLI11
        PRIVATE fmt::fmt-header-only
)
INSTALL(TARGETS ${CMAKE_PROJECT_NAME} DESTINATION bin)

